baseURL: "lianaak.github.io" 
title: Liana Akobian
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 2
        - name: Talks
          url: talks/
          weight: 3
        - name: Notes
          url: notes/
          weight: 4 

params:
    description: "This website hosts Liana Akobian's cv, projects, notes,.."
    author: "Liana Akobian"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","talks","notes"]
    ShowToc: false
    disableScrollToTop: false
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Liana Akobian
          subtitle: "I am a research assistant in Alex Cayco-Gajic lab at PSL-ENS (École Normale Supérieure). My research focuses on using and developing computational tools to dissect neural dynamics. I have a Bachelor's degree in Computer Science from the University of Vienna and a Master's degree in Data Science from the Technical University of Vienna. I am currently working on identifiying interpretable representations of connectivity weights in recurrent neural networks."
          imageUrl: picture.jpeg
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Talks
              url: talks/
            - name: Notes
              url: notes/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:liana.akobian@ens.psl.eu
        - name: GitHub
          url: https://github.com/lianaak
        - name: YouTube
          url: https://www.youtube.com/@lianaakobian
        - name: Bluesky
          url: https://bsky.app/profile/lakobian.bsky.social

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Liana Akobian"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2